In [89]:
import math

#### Numpy
The fundamental package for scientific computing with python

In [90]:
# Importing numpy
import numpy as np

In [91]:
list1 = [2,3,4,6,7,8]
list2 = [45,34,23,45,12,4]

In [92]:
list1.index(3)

1

In [93]:
list1+list2  # Cant add up the lists

[2, 3, 4, 6, 7, 8, 45, 34, 23, 45, 12, 4]

In [94]:
total = []    # Required a loop to add the 2 lists together, 
for num in list1:
    total1 = num+list2[list1.index(num)]
    total.append(total1)


In [95]:
total

[47, 37, 27, 51, 19, 12]

NumPy, which stands for Numerical Python, is a Python library primarily used for working with arrays and to perform a wide variety of mathematical operations on them

The use of Numpy

In [96]:
num1 = np.array(list1)  # Prints an array
num1

array([2, 3, 4, 6, 7, 8])

In [97]:
num2 = np.array(list2)
num2

array([45, 34, 23, 45, 12,  4])

In [98]:
total_array = num1 + num2  # Dont need a loop to add the 2 arrays together
total_array

array([47, 37, 27, 51, 19, 12])

In [99]:
total_array[2:5]

array([27, 51, 19])

In [100]:
total_array>29

array([ True,  True, False,  True, False, False])

In [101]:
total_array[[ True,  True, False,  True, False, False]]

array([47, 37, 51])

In [102]:
total_array[total_array>29]

array([47, 37, 51])

In [103]:
total_array.ndim   # attributes --> one dimensional array

1

#### 2D array


In [104]:
arr = np.array([[1, 2, 3,5], [4, 5, 6,5],[7,4,2,5]])

In [105]:
arr

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 4, 2, 5]])

In [106]:
arr[2,0]

7

In [107]:
arr.sum()

49

In [108]:
np.sum(arr[:,2])

11

In [109]:
np.sum(arr[2:])

18

In [110]:
from numpy import random

In [111]:
random.rand()  # Generating a number each time between 0 to 1

0.8059885320352591

In [112]:
random.rand(10)  # generating random number 10 times

array([0.34347897, 0.92818992, 0.95364687, 0.0686861 , 0.98379831,
       0.44500586, 0.78661045, 0.04172684, 0.18439884, 0.29258827])

In [113]:
random.rand(3)*10   # * 10 now changes the random generator 1 to 10

array([2.8814815 , 6.12430982, 1.70887891])

In [114]:
random.randint(5+1, size=(4))

array([3, 0, 0, 5])